#Robocode Compiler Properties
#Fri Oct 09 19:16:19 GMT-03:00 2026
compiler.binary=javac
compiler.classpath=-classpath libs/robocode.jar\:/home/aluno/Robifsc/robocode/robots
compiler.options=-verbose -encoding UTF-8
robocode.version=1.11.1
