#Robocode Properties
#Fri Oct 09 19:49:57 GMT-03:00 2026
robocode.cpu.constant=2128147
robocode.options.battle.desiredTPS=10000
robocode.options.rendering.antialiasing=0
robocode.options.rendering.method=0
robocode.options.rendering.text.antialiasing=0
robocode.version.lastrun=1.11.1
robocode.versionchecked=10/09/2026 18\:59\:56
