#Robocode window sizes
#Fri Oct 09 19:49:57 GMT-03:00 2026
net.sf.robocode.ui.dialog.ConsoleDialog=710,340,500,400
net.sf.robocode.ui.dialog.NewBattleDialog=534,215,850,650
net.sf.robocode.ui.dialog.RobocodeFrame=503,186,913,708
net.sf.robocode.ui.editor.RobocodeEditor=586,231,750,618
